#pragma once

#include "Common/Common.h"
#include <Windows.h>

namespace Wanted
{
	// 콘솔에 텍스트 색상 등을 지정할 때 사용할
	// 색상 열거형.
	enum class WANTED_API Color : unsigned short
	{
        BLACK = 0,
        DARKBLUE = FOREGROUND_BLUE,
        DARKGREEN = FOREGROUND_GREEN,
        DARKCYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,
        DARKRED = FOREGROUND_RED,
        DARKMAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
        DARKYELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
        DARKGRAY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
        BGDARKGRAY = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
        GRAY = FOREGROUND_INTENSITY,
        BGGRAY =  BACKGROUND_RED | BACKGROUND_GREEN,
        BLUE = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
        GREEN = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
        CYAN = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
        RED = FOREGROUND_INTENSITY | FOREGROUND_RED,
        MAGENTA = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
        YELLOW = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
        WHITE = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
        BGYELLOW = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
        BGDARKYELLOW = BACKGROUND_RED | BACKGROUND_GREEN,
        DARKYELLOWANDBGGRAY = FOREGROUND_RED | FOREGROUND_GREEN | BACKGROUND_INTENSITY,
        BGRED = BACKGROUND_INTENSITY | BACKGROUND_RED,
        DARKYELLOWANDBGYELLOW = FOREGROUND_RED | FOREGROUND_GREEN | BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
        YELLOWANDBGDARKYELLOW = YELLOW | BGDARKYELLOW,
        // enemyState color.
        BGYELLOWDARKYELLOW = BGYELLOW | DARKYELLOW,
        BGYELLOWDARKRED = BGYELLOW | DARKRED,
        BGYELLOWRED = BGYELLOW | RED,
        BGYELLOWDARKBLUE = BGYELLOW | DARKBLUE,
        BGYELLOWCYAN = BGYELLOW | CYAN,
        BGYELLOWDARKCYAN = BGYELLOW | DARKCYAN,
        BGYELLOWDARKMAGENTA = BGYELLOW | DARKMAGENTA,

        BGYELLOWGREEN = BGYELLOW | FOREGROUND_INTENSITY | FOREGROUND_GREEN
	};
}